<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogBooksSeeder extends Seeder
{
    public function run(): void
    {
        $catPendidikan = Category::firstOrCreate(['name' => 'Pendidikan'], ['level' => 1]);
        $catAnak = Category::firstOrCreate(['name' => 'Anak'], ['level' => 1]);
        $catRemaja = Category::firstOrCreate(['name' => 'Remaja'], ['level' => 1]);
        $catDewasa = Category::firstOrCreate(['name' => 'Dewasa'], ['level' => 1]);

        $catalog = [
            // ================== PENDIDIKAN ==================
            // SD
            [
                'title' => 'Matematika Ceria Kelas 4 SD',
                'author' => 'Budi Santoso, M.Pd.',
                'publisher' => 'Erlangga Edukasi',
                'publication_year' => 2022,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SD',
                'education_level' => 'SD',
                'stock' => 10,
                'available_stock' => 8,
                'description' => 'Buku pelajaran matematika interaktif untuk kelas 4 SD dengan ilustrasi berwarna dan soal latihan kontekstual.',
                'call_number' => '372.7 BUD m',
                'kode_buku' => 'BK-SD-001',
                'rak' => 'R1',
            ],
            [
                'title' => 'Ilmu Pengetahuan Alam dan Sosial (IPAS) SD',
                'author' => 'Siti Aminah, S.Pd.',
                'publisher' => 'Yudhistira',
                'publication_year' => 2023,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SD',
                'education_level' => 'SD',
                'stock' => 12,
                'available_stock' => 10,
                'description' => 'Kurikulum merdeka IPAS SD menyelami sains dan geografi nusantara dengan pendekatan inkuiri.',
                'call_number' => '372.3 SIT i',
                'kode_buku' => 'BK-SD-002',
                'rak' => 'R1',
            ],
            [
                'title' => 'Bahasa Indonesia: Pintar Membaca & Menulis SD',
                'author' => 'Hendra Setiawan',
                'publisher' => 'Balai Pustaka',
                'publication_year' => 2021,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SD',
                'education_level' => 'SD',
                'stock' => 8,
                'available_stock' => 7,
                'description' => 'Melatih kemampuan literasi dan daya nalar dasar anak sekolah dasar.',
                'call_number' => '372.6 HEN b',
                'kode_buku' => 'BK-SD-003',
                'rak' => 'R1',
            ],
            [
                'title' => 'Pendidikan Pancasila & Kewarganegaraan SD',
                'author' => 'Dewi Lestari, S.Pd.',
                'publisher' => 'Pusat Perbukuan Kemdikbud',
                'publication_year' => 2023,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SD',
                'education_level' => 'SD',
                'stock' => 15,
                'available_stock' => 12,
                'description' => 'Membangun karakter profil pelajar Pancasila melalui kisah keteladanan dan gotong royong.',
                'call_number' => '370.11 DEW p',
                'kode_buku' => 'BK-SD-004',
                'rak' => 'R1',
            ],

            // SMP
            [
                'title' => 'Matematika Terpadu untuk SMP/MTs Kelas VII',
                'author' => 'Prof. Dr. Marsigit',
                'publisher' => 'Quadra',
                'publication_year' => 2022,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMP',
                'education_level' => 'SMP',
                'stock' => 10,
                'available_stock' => 9,
                'description' => 'Konsep aljabar, geometri, dan statistika awal dengan pemecahan masalah bertahap.',
                'call_number' => '510 MAR m',
                'kode_buku' => 'BK-SMP-001',
                'rak' => 'R2',
            ],
            [
                'title' => 'IPA Terpadu: Fisika & Biologi SMP',
                'author' => 'Drs. Supriyadi, M.Si.',
                'publisher' => 'Erlangga',
                'publication_year' => 2023,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMP',
                'education_level' => 'SMP',
                'stock' => 14,
                'available_stock' => 11,
                'description' => 'Eksperimen laboratorium sederhana dan fenomena sains kehidupan sehari-hari bagi siswa SMP.',
                'call_number' => '500 SUP i',
                'kode_buku' => 'BK-SMP-002',
                'rak' => 'R2',
            ],
            [
                'title' => 'English in Focus for Junior High School',
                'author' => 'Artono Wardiman',
                'publisher' => 'Kemdikbudristek',
                'publication_year' => 2021,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMP',
                'education_level' => 'SMP',
                'stock' => 10,
                'available_stock' => 8,
                'description' => 'Buku teks bahasa Inggris interaktif dengan audio listening dan latihan percakapan.',
                'call_number' => '420 WAR e',
                'kode_buku' => 'BK-SMP-003',
                'rak' => 'R2',
            ],
            [
                'title' => 'Ilmu Pengetahuan Sosial: Dinamika Kehidupan Bangsa',
                'author' => 'I Wayan Legawa',
                'publisher' => 'Tiga Serangkai',
                'publication_year' => 2022,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMP',
                'education_level' => 'SMP',
                'stock' => 9,
                'available_stock' => 7,
                'description' => 'Menelaah interaksi antarruang di Asia Tenggara serta perkembangan ekonomi nasional.',
                'call_number' => '300 LEG i',
                'kode_buku' => 'BK-SMP-004',
                'rak' => 'R2',
            ],

            // SMA
            [
                'title' => 'Fisika Lanjutan untuk SMA/MA Kelas XI',
                'author' => 'Marthen Kanginan',
                'publisher' => 'Erlangga',
                'publication_year' => 2023,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMA',
                'education_level' => 'SMA',
                'stock' => 15,
                'available_stock' => 13,
                'description' => 'Kajian mendalam mekanika fluida, termodinamika, gelombang mekanik, dan optika geometri.',
                'call_number' => '530 MAR f',
                'kode_buku' => 'BK-SMA-001',
                'rak' => 'R3',
            ],
            [
                'title' => 'Biologi Sel & Genetika Siswa SMA',
                'author' => 'Dr. Irnaningsih',
                'publisher' => 'Erlangga',
                'publication_year' => 2022,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMA',
                'education_level' => 'SMA',
                'stock' => 12,
                'available_stock' => 10,
                'description' => 'Memahami DNA, mutasi, sintesis protein, dan pewarisan sifat makhluk hidup.',
                'call_number' => '570 IRN b',
                'kode_buku' => 'BK-SMA-002',
                'rak' => 'R3',
            ],
            [
                'title' => 'Kimia Stoikiometri & Struktur Atom SMA',
                'author' => 'Unggul Sudarmo',
                'publisher' => 'Erlangga',
                'publication_year' => 2023,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMA',
                'education_level' => 'SMA',
                'stock' => 10,
                'available_stock' => 8,
                'description' => 'Trik cerdas memahami ikatan kimia, reaksi redoks, dan perhitungan massa molar.',
                'call_number' => '540 UNG k',
                'kode_buku' => 'BK-SMA-003',
                'rak' => 'R3',
            ],
            [
                'title' => 'Kalkulus & Matematika Peminatan SMA',
                'author' => 'Sukino',
                'publisher' => 'Erlangga',
                'publication_year' => 2021,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMA',
                'education_level' => 'SMA',
                'stock' => 11,
                'available_stock' => 9,
                'description' => 'Limit fungsi trigonometri, turunan, dan integral aplikasi persiapan seleksi perguruan tinggi.',
                'call_number' => '515 SUK k',
                'kode_buku' => 'BK-SMA-004',
                'rak' => 'R3',
            ],
            [
                'title' => 'Ekonomi & Akuntansi Keuangan SMA',
                'author' => 'Alam S.',
                'publisher' => 'Esis',
                'publication_year' => 2022,
                'category_id' => $catPendidikan->id,
                'main_category' => 'Pendidikan',
                'sub_category' => 'SMA',
                'education_level' => 'SMA',
                'stock' => 10,
                'available_stock' => 8,
                'description' => 'Mempelajari siklus akuntansi perusahaan jasa dan dagang serta kebijakan fiskal negara.',
                'call_number' => '330 ALA e',
                'kode_buku' => 'BK-SMA-005',
                'rak' => 'R3',
            ],

            // ================== ANAK-ANAK ==================
            // Fiksi
            [
                'title' => 'Petualangan Si Kancil di Hutan Ajaib',
                'author' => 'Rahayu Lestari',
                'publisher' => 'Bentang Kids',
                'publication_year' => 2021,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 8,
                'available_stock' => 6,
                'description' => 'Kisah seru kancil cerdik yang menolong hewan-hewan lain dari bahaya dengan akal bijaknya.',
                'call_number' => '899.2 RAH p',
                'kode_buku' => 'BK-ANK-001',
                'rak' => 'R4',
            ],
            [
                'title' => 'Sahabat dari Bintang Kecil',
                'author' => 'Tika Sukmawati',
                'publisher' => 'Noura Books',
                'publication_year' => 2022,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 7,
                'available_stock' => 5,
                'description' => 'Fiksi imajinatif tentang persahabatan anak bumi dan makhluk ramah dari konstelasi Andromeda.',
                'call_number' => '899.2 TIK s',
                'kode_buku' => 'BK-ANK-002',
                'rak' => 'R4',
            ],
            // Dongeng
            [
                'title' => 'Kumpulan Dongeng Klasik Nusantara',
                'author' => 'Tim Balai Pustaka',
                'publisher' => 'Balai Pustaka',
                'publication_year' => 2020,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 10,
                'available_stock' => 9,
                'description' => 'Memuat dongeng legendaris Malin Kundang, Danau Toba, Keong Mas, dan Timun Mas.',
                'call_number' => '398.2 TIM k',
                'kode_buku' => 'BK-ANK-003',
                'rak' => 'R4',
            ],
            [
                'title' => 'Kisah Abu Nawas Penuh Hikmah',
                'author' => 'Abdul Hadi W.M.',
                'publisher' => 'Mizan Fantasi',
                'publication_year' => 2021,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 6,
                'available_stock' => 6,
                'description' => 'Cerita jenaka namun sarat hikmah kecerdasan dari sang tokoh legendaris Baghdad.',
                'call_number' => '398.2 ABD k',
                'kode_buku' => 'BK-ANK-004',
                'rak' => 'R4',
            ],
            // Cerita Bergambar
            [
                'title' => 'Milo Si Kucing Pemberani',
                'author' => 'Clara Ng',
                'publisher' => 'Gramedia Pustaka Utama',
                'publication_year' => 2023,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 12,
                'available_stock' => 11,
                'description' => 'Buku cerita bergambar penuh warna dengan pesan tentang keberanian mencoba hal baru.',
                'call_number' => '741.5 CLA m',
                'kode_buku' => 'BK-ANK-005',
                'rak' => 'R4',
            ],
            [
                'title' => 'Dino Si Dinosaurus Ramah',
                'author' => 'Rani Novita',
                'publisher' => 'Bhuana Ilmu Populer',
                'publication_year' => 2022,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 9,
                'available_stock' => 8,
                'description' => 'Ilustrasi lucu tentang seekor dinosaurus yang belajar berbagi mainan bersama teman.',
                'call_number' => '741.5 RAN d',
                'kode_buku' => 'BK-ANK-006',
                'rak' => 'R4',
            ],
            // Edukasi Anak
            [
                'title' => 'Ensiklopedia Bergambar: Mengenal Hewan Laut',
                'author' => 'Dr. Wahyu Tri',
                'publisher' => 'Elex Media Komputindo',
                'publication_year' => 2022,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 10,
                'available_stock' => 9,
                'description' => 'Fakta menakjubkan tentang paus biru, terumbu karang, dan makhluk misterius laut dalam.',
                'call_number' => '591.77 WAH e',
                'kode_buku' => 'BK-ANK-007',
                'rak' => 'R4',
            ],
            [
                'title' => 'Eksperimen Sains Seru di Rumah',
                'author' => 'Fitria Wardhani',
                'publisher' => 'Cikal Aksara',
                'publication_year' => 2023,
                'category_id' => $catAnak->id,
                'main_category' => 'Anak-Anak',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 11,
                'available_stock' => 10,
                'description' => '50 percobaan sains aman dan mengasyikkan menggunakan bahan dapur sehari-hari.',
                'call_number' => '507.8 FIT e',
                'kode_buku' => 'BK-ANK-008',
                'rak' => 'R4',
            ],

            // ================== REMAJA ==================
            // Fiksi
            [
                'title' => 'Langit di Balik Jendela Sekolah',
                'author' => 'Raditya Pratama',
                'publisher' => 'GagasMedia',
                'publication_year' => 2022,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 8,
                'available_stock' => 7,
                'description' => 'Kisah persahabatan lima siswa SMA dalam mengejar mimpi menjadi musisi indie.',
                'call_number' => '899.2 RAD l',
                'kode_buku' => 'BK-RMJ-001',
                'rak' => 'R5',
            ],
            // Novel
            [
                'title' => 'Negeri Lima Menara',
                'author' => 'A. Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'publication_year' => 2019,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 14,
                'available_stock' => 12,
                'description' => 'Mantra man jadda wajada mengiringi persahabatan enam santri dari berbagai pelosok negeri.',
                'call_number' => '899.2 FUA n',
                'kode_buku' => 'BK-RMJ-002',
                'rak' => 'R5',
            ],
            [
                'title' => 'Hujan',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'publication_year' => 2020,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 16,
                'available_stock' => 14,
                'description' => 'Tentang persahabatan, cinta, melupakan, dan teknologi masa depan pasca bencana dahsyat.',
                'call_number' => '899.2 TER h',
                'kode_buku' => 'BK-RMJ-003',
                'rak' => 'R5',
            ],
            [
                'title' => 'Dilan 1990: Dia adalah Dilanku',
                'author' => 'Pidi Baiq',
                'publisher' => 'Pastel Books',
                'publication_year' => 2018,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 12,
                'available_stock' => 9,
                'description' => 'Kisah romansa manis anak SMA di Kota Bandung era 90-an dengan gaya puitis humoris.',
                'call_number' => '899.2 PID d',
                'kode_buku' => 'BK-RMJ-004',
                'rak' => 'R5',
            ],
            // Komik
            [
                'title' => 'Si Juki: Berani Gagal',
                'author' => 'Faza Meonk',
                'publisher' => 'Bukune',
                'publication_year' => 2021,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 9,
                'available_stock' => 8,
                'description' => 'Komik strip komedi satir mengenai lika-liku kehidupan pemuda masa kini.',
                'call_number' => '741.5 FAZ s',
                'kode_buku' => 'BK-RMJ-005',
                'rak' => 'R5',
            ],
            [
                'title' => 'Gundala Putra Petir Reborn',
                'author' => 'Hasmi & Bumilangit',
                'publisher' => 'Koloni',
                'publication_year' => 2020,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 7,
                'available_stock' => 6,
                'description' => 'Kebangkitan pahlawan super Indonesia dalam format visual modern penuh aksi.',
                'call_number' => '741.5 HAS g',
                'kode_buku' => 'BK-RMJ-006',
                'rak' => 'R5',
            ],
            // Pengembangan Diri
            [
                'title' => 'The 7 Habits of Highly Effective Teens',
                'author' => 'Sean Covey',
                'publisher' => 'Binarupa Aksara',
                'publication_year' => 2021,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 11,
                'available_stock' => 10,
                'description' => 'Panduan praktis remaja membangun visi hidup, disiplin diri, dan relasi positif.',
                'call_number' => '158.1 COV s',
                'kode_buku' => 'BK-RMJ-007',
                'rak' => 'R5',
            ],
            [
                'title' => 'Temukan Bakat & Passion-mu Sejak Muda',
                'author' => 'Ahmad Rifa\'i Rif\'an',
                'publisher' => 'Elex Media Komputindo',
                'publication_year' => 2022,
                'category_id' => $catRemaja->id,
                'main_category' => 'Remaja',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 8,
                'available_stock' => 7,
                'description' => 'Langkah nyata mengenali potensi unik diri untuk merancang karier masa depan gemilang.',
                'call_number' => '158.1 AHM t',
                'kode_buku' => 'BK-RMJ-008',
                'rak' => 'R5',
            ],

            // ================== DEWASA ==================
            // Fiksi
            [
                'title' => 'Laut Bercerita',
                'author' => 'Leila S. Chudori',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'publication_year' => 2021,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 15,
                'available_stock' => 12,
                'description' => 'Kisah haru para aktivis mahasiswa 1998 dan suara mereka yang tak pernah padam di kedalaman laut.',
                'call_number' => '899.2 LEI l',
                'kode_buku' => 'BK-DWS-001',
                'rak' => 'R6',
            ],
            [
                'title' => 'Cantik Itu Luka',
                'author' => 'Eka Kurniawan',
                'publisher' => 'Gramedia Pustaka Utama',
                'publication_year' => 2020,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Fiksi',
                'education_level' => null,
                'stock' => 10,
                'available_stock' => 8,
                'description' => 'Realisme magis berlatar kota pesisir Halimunda menelusuri luka sejarah dan takdir keluarga.',
                'call_number' => '899.2 EKA c',
                'kode_buku' => 'BK-DWS-002',
                'rak' => 'R6',
            ],
            // Non Fiksi
            [
                'title' => 'Sapiens: Riwayat Singkat Umat Manusia',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'KPG',
                'publication_year' => 2020,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 18,
                'available_stock' => 15,
                'description' => 'Eksplorasi memukau tentang bagaimana kera tak berarti bisa menjadi penguasa planet Bumi.',
                'call_number' => '909 HAR s',
                'kode_buku' => 'BK-DWS-003',
                'rak' => 'R6',
            ],
            [
                'title' => 'Filosofi Teras: Stoikisme Kuno untuk Mental Tangguh',
                'author' => 'Henry Manampiring',
                'publisher' => 'Kompas Gramedia',
                'publication_year' => 2022,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 20,
                'available_stock' => 16,
                'description' => 'Menerapkan filsafat stoikisme Yunani-Romawi kuno untuk mengatasi kecemasan hidup modern.',
                'call_number' => '188 MAN f',
                'kode_buku' => 'BK-DWS-004',
                'rak' => 'R6',
            ],
            // Bisnis
            [
                'title' => 'The Psychology of Money',
                'author' => 'Morgan Housel',
                'publisher' => 'Baca',
                'publication_year' => 2021,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 16,
                'available_stock' => 13,
                'description' => 'Pelajaran abadi mengenai kekayaan, ketamakan, dan kebahagiaan finansial personal.',
                'call_number' => '332.024 HOU p',
                'kode_buku' => 'BK-DWS-005',
                'rak' => 'R6',
            ],
            [
                'title' => 'Zero to One: Catatan Membangun Masa Depan',
                'author' => 'Peter Thiel',
                'publisher' => 'Gramedia Pustaka Utama',
                'publication_year' => 2020,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 11,
                'available_stock' => 9,
                'description' => 'Cara berpikir inovatif untuk menciptakan hal yang belum pernah ada sebelumnya di dunia bisnis.',
                'call_number' => '658.4 THI z',
                'kode_buku' => 'BK-DWS-006',
                'rak' => 'R6',
            ],
            // Teknologi
            [
                'title' => 'Kecerdasan Buatan dan Transformasi Digital',
                'author' => 'Dr. Richardus Eko Indrajit',
                'publisher' => 'Andi Offset',
                'publication_year' => 2023,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 12,
                'available_stock' => 11,
                'description' => 'Implementasi kecerdasan buatan, big data, dan machine learning dalam industri modern.',
                'call_number' => '006.3 IND k',
                'kode_buku' => 'BK-DWS-007',
                'rak' => 'R6',
            ],
            [
                'title' => 'Arsitektur Web Modern dan Cloud Computing',
                'author' => 'Bambang Hariyanto',
                'publisher' => 'Informatika',
                'publication_year' => 2023,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 10,
                'available_stock' => 9,
                'description' => 'Membangun aplikasi terdistribusi, microservices, dan deployment andal di infrastruktur cloud.',
                'call_number' => '004.6 HAR a',
                'kode_buku' => 'BK-DWS-008',
                'rak' => 'R6',
            ],
            // Pendidikan
            [
                'title' => 'Pedagogi Kritis: Pendidikan Pembebasan Abad 21',
                'author' => 'Paulo Freire (Terjemahan Mansour Fakih)',
                'publisher' => 'Narasi',
                'publication_year' => 2021,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 8,
                'available_stock' => 7,
                'description' => 'Filsafat pendidikan kritis yang memanusiakan manusia serta membangun kesadaran kritis sosial.',
                'call_number' => '370.1 FRE p',
                'kode_buku' => 'BK-DWS-009',
                'rak' => 'R6',
            ],
            [
                'title' => 'Metode Penelitian Pendidikan Kuantitatif & Kualitatif',
                'author' => 'Prof. Dr. Sugiyono',
                'publisher' => 'Alfabeta',
                'publication_year' => 2022,
                'category_id' => $catDewasa->id,
                'main_category' => 'Dewasa',
                'sub_category' => 'Non Fiksi',
                'education_level' => null,
                'stock' => 14,
                'available_stock' => 12,
                'description' => 'Metodologi komprehensif untuk penelitian tesis, disertasi, dan karya ilmiah bidang pendidikan.',
                'call_number' => '001.42 SUG m',
                'kode_buku' => 'BK-DWS-010',
                'rak' => 'R6',
            ],
        ];

        // First update or insert the curated catalog
        $existingBooks = Book::orderBy('id')->get();
        $index = 0;

        foreach ($catalog as $item) {
            $data = [
                'judul_buku'      => $item['title'] ?? $item['judul_buku'] ?? 'Judul Buku',
                'sku'             => 'SKU-' . str_pad($index + 1, 5, '0', STR_PAD_LEFT),
                'penulis'         => $item['author'] ?? $item['penulis'] ?? 'Penulis',
                'category_id'     => $item['category_id'] ?? $catPendidikan->id,
                'main_category'   => $item['main_category'] ?? null,
                'sub_category'    => $item['sub_category'] ?? null,
                'education_level' => $item['education_level'] ?? null,
                'subcategory_id'  => null,
                'stok'            => $item['available_stock'] ?? $item['stock'] ?? 10,
                'status'          => 'Tersedia',
                'no_iventaris'    => 'INV/' . date('Y') . '/' . str_pad($index + 1, 4, '0', STR_PAD_LEFT),
                'kode_buku'       => $item['kode_buku'] ?? ('BK-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT)),
                'ddc'             => $item['call_number'] ?? null,
                'rak'             => $item['rak'] ?? 'A1',
                'edition'         => 'Cetakan ke-1',
            ];

            if (isset($existingBooks[$index])) {
                $book = $existingBooks[$index];
                $book->update($data);
            } else {
                Book::create($data);
            }
            $index++;
        }

        // If there are remaining existing books beyond catalog, assign them evenly
        while ($index < count($existingBooks)) {
            $book = $existingBooks[$index];
            // Assign leftover books distributed among categories
            $mod = $index % 4;
            if ($mod === 0) {
                $book->update([
                    'judul_buku' => 'Buku Referensi Pembelajaran SD ' . ($index + 1),
                    'category_id' => $catPendidikan->id,
                    'main_category' => 'Pendidikan',
                    'sub_category' => 'SD',
                    'education_level' => 'SD',
                ]);
            } elseif ($mod === 1) {
                $book->update([
                    'judul_buku' => 'Petualangan Sains Anak ' . ($index + 1),
                    'category_id' => $catAnak->id,
                    'main_category' => 'Anak-Anak',
                    'sub_category' => 'Non Fiksi',
                    'education_level' => null,
                ]);
            } elseif ($mod === 2) {
                $book->update([
                    'judul_buku' => 'Kisah Inspiratif Remaja ' . ($index + 1),
                    'category_id' => $catRemaja->id,
                    'main_category' => 'Remaja',
                    'sub_category' => 'Fiksi',
                    'education_level' => null,
                ]);
            } else {
                $book->update([
                    'judul_buku' => 'Wawasan Manajemen Modern ' . ($index + 1),
                    'category_id' => $catDewasa->id,
                    'main_category' => 'Dewasa',
                    'sub_category' => 'Non Fiksi',
                    'education_level' => null,
                ]);
            }
            $index++;
        }

        // Seed notifications for user 2 (or first user)
        $testUser = \App\Models\User::where('role', 'user')->first();
        if ($testUser) {
            \App\Models\AppNotification::where('user_id', $testUser->id)->delete();

            $notifications = [
                [
                    'user_id' => $testUser->id,
                    'role' => 'user',
                    'type' => 'reservation_approved',
                    'title' => 'Reservasi Buku Disetujui',
                    'message' => 'Pengajuan reservasi buku "Fisika Lanjutan untuk SMA Kelas XI" telah disetujui. Silakan ambil buku di meja sirkulasi.',
                    'is_read' => false,
                    'created_at' => now()->subMinutes(15),
                ],
                [
                    'user_id' => $testUser->id,
                    'role' => 'user',
                    'type' => 'reservation_pending',
                    'title' => 'Reservasi Menunggu Verifikasi',
                    'message' => 'Permohonan reservasi buku "Filosofi Teras" sedang menunggu konfirmasi staf perpustakaan.',
                    'is_read' => false,
                    'created_at' => now()->subHours(2),
                ],
                [
                    'user_id' => $testUser->id,
                    'role' => 'user',
                    'type' => 'info_announcement',
                    'title' => 'Pengumuman Koleksi Buku Baru',
                    'message' => 'Koleksi buku Kurikulum Merdeka SD, SMP, SMA, dan novel remaja terbaru kini telah tersedia di katalog.',
                    'is_read' => false,
                    'created_at' => now()->subHours(5),
                ],
                [
                    'user_id' => $testUser->id,
                    'role' => 'user',
                    'type' => 'reservation_rejected',
                    'title' => 'Reservasi Buku Ditolak',
                    'message' => 'Reservasi buku "Laut Bercerita" tidak dapat disetujui karena stok fisik sedang dalam proses konservasi.',
                    'is_read' => true,
                    'created_at' => now()->subDays(1),
                ],
                [
                    'user_id' => $testUser->id,
                    'role' => 'user',
                    'type' => 'borrowing_approved',
                    'title' => 'Peminjaman Buku Disetujui',
                    'message' => 'Peminjaman buku "Matematika Ceria Kelas 4 SD" telah disetujui. Batas pengembalian adalah 7 hari dari sekarang.',
                    'is_read' => true,
                    'created_at' => now()->subDays(2),
                ],
                [
                    'user_id' => $testUser->id,
                    'role' => 'user',
                    'type' => 'info_system',
                    'title' => 'Pemberitahuan Jam Layanan',
                    'message' => 'Layanan peminjaman dan pengembalian perpustakaan buka setiap hari kerja pukul 08.00 - 16.00 WIB.',
                    'is_read' => true,
                    'created_at' => now()->subDays(3),
                ],
            ];

            foreach ($notifications as $notif) {
                \App\Models\AppNotification::create($notif);
            }
        }
    }
}
