<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Member;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        Member::insert([
            [
                'member_number' => 'M001',
                'name' => 'Ahmad Fauzan',
                'nis_nip' => '1234567890',
                'gender' => 'Laki-laki',
                'class' => 'XII IPA 1',
                'email' => 'ahmad@example.com',
                'phone' => '081234567801',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M002',  
                'name' => 'Budi Santoso',
                'nis_nip' => '0987654321',
                'gender' => 'Laki-laki',
                'class' => 'XII IPA 1',
                'email' => 'budi@example.com',
                'phone' => '081234567802',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M003',
                'name' => 'Citra Lestari',
                'nis_nip' => '1111111111',
                'gender' => 'Perempuan',
                'class' => 'XII IPA 1',
                'email' => 'citra@example.com',
                'phone' => '081234567803',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M004',
                'name' => 'Dimas Pratama',
                'nis_nip' => '2222222222',
                'gender' => 'Laki-laki',
                'class' => 'XII IPA 1',
                'email' => 'dimas@example.com',
                'phone' => '081234567804',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M005',
                'name' => 'Eka Putri',
                'nis_nip' => '3333333333',
                'gender' => 'Perempuan',
                'class' => 'XII IPA 1',
                'email' => 'eka@example.com',
                'phone' => '081234567805',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M006',
                'name' => 'Fajar Ramadhan',
                'nis_nip' => '4444444444',
                'gender' => 'Laki-laki',
                'class' => 'XII IPA 1',
                'email' => 'fajar@example.com',
                'phone' => '081234567806',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M007',
                'name' => 'Gita Maharani',
                'nis_nip' => '5555555555',
                'gender' => 'Perempuan',
                'class' => 'XII IPA 1',
                'email' => 'gita@example.com',
                'phone' => '081234567807',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M008',
                'name' => 'Hendra Wijaya',
                'nis_nip' => '6666666666',
                'gender' => 'Laki-laki',
                'class' => 'XII IPA 1',
                'email' => 'hendra@example.com',
                'phone' => '081234567808',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M009',
                'name' => 'Intan Permata',
                'nis_nip' => '7777777777',
                'gender' => 'Perempuan',
                'class' => 'XII IPA 1',
                'email' => 'intan@example.com',
                'phone' => '081234567809',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
            [
                'member_number' => 'M010',
                'name' => 'Joko Setiawan',
                'nis_nip' => '8888888888',
                'gender' => 'Laki-laki',
                'class' => 'XII IPA 1',
                'email' => 'joko@example.com',
                'phone' => '081234567810',
                'address' => 'Surakarta',
                'status' => 'aktif',
                'registered_at' => now(),
            ],
        ]);
    }
}
